-- Khetha NCAP Supabase schema. Run in Supabase SQL Editor.
create extension if not exists "uuid-ossp";
create table if not exists profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text, language text default 'English', province text, accessibility_needs text[], consent_at timestamptz, created_at timestamptz default now());
create table if not exists careers (id uuid primary key default uuid_generate_v4(), slug text unique not null, title text not null, description text, skills text[], subjects text[], education_path text, salary_range text, created_at timestamptz default now());
create table if not exists qualifications (id uuid primary key default uuid_generate_v4(), title text not null, description text, nqf_level text, duration text, field text, provider_id uuid, created_at timestamptz default now());
create table if not exists providers (id uuid primary key default uuid_generate_v4(), name text not null, provider_type text, province text, city text, address text, website text, phone text, latitude numeric, longitude numeric, created_at timestamptz default now());
alter table qualifications add constraint qualifications_provider_fk foreign key (provider_id) references providers(id) on delete set null;
create table if not exists assessments (id uuid primary key default uuid_generate_v4(), user_id uuid references auth.users(id) on delete cascade, type text check (type in ('subjects','career','job-fit')), score numeric, result jsonb, created_at timestamptz default now());
create table if not exists assessment_answers (id uuid primary key default uuid_generate_v4(), assessment_id uuid references assessments(id) on delete cascade, question_key text not null, answer jsonb not null);
create table if not exists favourites (user_id uuid references auth.users(id) on delete cascade, item_type text check (item_type in ('career','qualification','provider')), item_id uuid not null, created_at timestamptz default now(), primary key (user_id,item_type,item_id));
create table if not exists notifications (id uuid primary key default uuid_generate_v4(), user_id uuid references auth.users(id) on delete cascade, title text not null, body text not null, read_at timestamptz, scheduled_for timestamptz, created_at timestamptz default now());
alter table profiles enable row level security; alter table assessments enable row level security; alter table assessment_answers enable row level security; alter table favourites enable row level security; alter table notifications enable row level security;
create policy "users manage own profile" on profiles for all using (auth.uid() = id) with check (auth.uid() = id);
create policy "users manage own assessments" on assessments for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users manage own answers" on assessment_answers for all using (exists (select 1 from assessments a where a.id=assessment_id and a.user_id=auth.uid())) with check (exists (select 1 from assessments a where a.id=assessment_id and a.user_id=auth.uid()));
create policy "users manage own favourites" on favourites for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users read own notifications" on notifications for select using (auth.uid() = user_id);
create policy "public read careers" on careers for select using (true); create policy "public read qualifications" on qualifications for select using (true); create policy "public read providers" on providers for select using (true);
insert into careers (slug,title,description,skills,subjects,education_path) values ('health-scientist','Health Scientist','Research and improve health outcomes for communities.',ARRAY['Research','Communication','Analysis'],ARRAY['Mathematics','Life Sciences','Physical Sciences'],'Diploma or degree'),('software-developer','Software Developer','Build digital products that solve real problems.',ARRAY['Logic','Creativity','Problem solving'],ARRAY['Mathematics','Information Technology'],'Diploma, degree or learnership') on conflict (slug) do nothing;
